#!/usr/bin/env node
'use strict';

/**
 * Generated by WebScraper — 2026-05-03T20:00:23.352Z
 * Run:  node workflow.js
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

const STEALTH_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

async function applyStealthToPage(page) {
  try {
    const client = await page.target().createCDPSession();
    await client.send('Emulation.setUserAgentOverride', {
      userAgent: STEALTH_UA,
      platform: 'Win32',
    });
    await client.send('Emulation.setLocaleOverride', { locale: 'en-US' }).catch(() => {});
    await client.send('Emulation.setTimezoneOverride', { timezoneId: 'America/New_York' }).catch(() => {});
    await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => false, configurable: true });
    });
  } catch (_) {}
}

/**
 * Try each selector in order; return the first ElementHandle that resolves.
 * selectors = [{ value: string, type: 'css'|'xpath' }, ...]
 */
async function resolveElement(page, selectors) {
  for (const { value, type } of selectors) {
    try {
      const selector =
        type === 'xpath'
          ? `::-p-xpath(${value})`
          : value;
      const el = await page.$(selector);
      if (el) return el;
    } catch (_) {}
  }
  return null;
}

/**
 * Same as resolveElement but returns ALL matching handles for the first
 * selector that yields at least one result.
 */
async function resolveElements(page, selectors) {
  for (const { value, type } of selectors) {
    try {
      const selector =
        type === 'xpath'
          ? `::-p-xpath(${value})`
          : value;

      const els = await page.$$(selector);
      if (els && els.length > 0) return els;
    } catch (_) {}
  }
  return [];
}

/**
 * Wait until any selector in the list appears within timeout ms.
 * Returns the ElementHandle of the first match found.
 * Throws if nothing resolves in time.
 */
async function waitForAny(page, selectors, timeout = 10000) {
  const deadline = Date.now() + timeout;
  let lastErr;
  while (Date.now() < deadline) {
    for (const { value, type } of selectors) {
      try {
        const el = type === 'xpath'
          ? (await page.$x(value))[0]
          : await page.$(value);
        if (el) return el;
      } catch (e) { lastErr = e; }
    }
    await new Promise(r => setTimeout(r, 200));
  }
  const tried = selectors.map(s => `[${s.type}] ${s.value}`).join(', ');
  throw new Error(`waitForAny: none matched within ${timeout}ms. Tried: ${tried}`);
}

/**
 * Run page.evaluate(fn, el) with XPath-aware element resolution.
 */
async function evalOnElement(page, selectors, fn) {
  const el = await resolveElement(page, selectors);
  if (!el) throw new Error('evalOnElement: element not found for selectors: ' + JSON.stringify(selectors));
  return page.evaluate(fn, el);
}

/**
 * Run page.evaluate(fn, el) on ALL elements matched by the first working selector.
 */
async function evalOnElements(page, selectors, fn) {
  const els = await resolveElements(page, selectors);
  if (!els.length) return [];
  return Promise.all(els.map(el => page.evaluate(fn, el)));
}

async function run() {
  const __results__ = {};

  const browser = await puppeteer.launch({
    // to delete:
    executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-blink-features=AutomationControlled',
      '--window-size=888,492',
    ],
  });

  let page = await browser.newPage();
  await applyStealthToPage(page);
  await page.setViewport({ width: 888, height: 492, deviceScaleFactor: 1 });
  await page.setExtraHTTPHeaders({ 'Accept-Language': 'en-US,en;q=0.9' });

  // Starting URL from recording session
  await page.goto("file:///C:/Users/MateuszAndryszak/Downloads/test-selectors-change.html", { waitUntil: 'networkidle2' });

  try {
    // Navigate
    await page.goto("file:///C:/Users/MateuszAndryszak/Downloads/test-selectors-change.html", {
      waitUntil: "load",
      timeout: 30000,
    });
    const _rows_3 = [];
    {
      const _els_0 = await page.$$("li.fruit-item");
      for (let i = 0; i < _els_0.length; i++) {
        const _el_1 = _els_0[i];
        const _row_2 = { _index: i + 1 };
          _row_2["Fruit"] = await _el_1.evaluate(e => (e.textContent || '').trim()).catch(() => '');
        _rows_3.push(_row_2);
      }
    }
    __results__["Fruits"] = _rows_3;
    const _rows_7 = [];
    {
      const _els_4 = await page.$$("tr.data-row");
      for (let i = 0; i < _els_4.length; i++) {
        const _el_5 = _els_4[i];
        const _row_6 = { _index: i + 1 };
          _row_6["Project"] = await _el_5.$eval("td:nth-child(2)", e => (e.textContent || '').trim()).catch(() => '');
          _row_6["Owner"] = await _el_5.$eval("td:nth-child(3)", e => (e.textContent || '').trim()).catch(() => '');
          _row_6["Score"] = await _el_5.$eval("td:nth-child(5)", e => (e.textContent || '').trim()).catch(() => '');
        _rows_7.push(_row_6);
      }
    }
    __results__["Table"] = _rows_7;
    const _rows_b = [];
    {
      const _els_8 = await page.$$("div.id-block");
      for (let i = 0; i < _els_8.length; i++) {
        const _el_9 = _els_8[i];
        const _row_a = { _index: i + 1 };
          _row_a["Metric name"] = await _el_9.$eval("div.id-block-name", e => (e.textContent || '').trim()).catch(() => '');
          _row_a["Metric value"] = await _el_9.$eval("div.id-block-val", e => (e.textContent || '').trim()).catch(() => '');
        _rows_b.push(_row_a);
      }
    }
    __results__["Metrics"] = _rows_b;
    const _rows_f = [];
    {
      const _els_c = await page.$$("div.product-card");
      for (let i = 0; i < _els_c.length; i++) {
        const _el_d = _els_c[i];
        const _row_e = { _index: i + 1 };
          _row_e["Price"] = await _el_d.$eval("span.product-price", e => (e.textContent || '').trim()).catch(() => '');
          _row_e["Reviews"] = await _el_d.$eval("span.product-rating", e => (e.textContent || '').trim()).catch(() => '');
        _rows_f.push(_row_e);
      }
    }
    __results__["Products"] = _rows_f;
    const _rows_j = [];
    {
      const _els_g = await page.$$("div.news-article");
      for (let i = 0; i < _els_g.length; i++) {
        const _el_h = _els_g[i];
        const _row_i = { _index: i + 1 };
          _row_i["Headline"] = await _el_h.$eval("div.news-headline", e => (e.textContent || '').trim()).catch(() => '');
          _row_i["Views"] = await _el_h.$eval("div.news-views", e => (e.textContent || '').trim()).catch(() => '');
        _rows_j.push(_row_i);
      }
    }
    __results__["News"] = _rows_j;
    const _rows_n = [];
    {
      const _els_k = await page.$$("#classless-list li");
      for (let i = 0; i < _els_k.length; i++) {
        const _el_l = _els_k[i];
        const _row_m = { _index: i + 1 };
          _row_m["Name"] = await _el_l.$eval("strong", e => (e.textContent || '').trim()).catch(() => '');
          _row_m["Value"] = await _el_l.$eval("b", e => (e.textContent || '').trim()).catch(() => '');
        _rows_n.push(_row_m);
      }
    }
    __results__["People"] = _rows_n;
    const _rows_r = [];
    {
      const _els_o = await page.$$("div.c-catalog__item");
      for (let i = 0; i < _els_o.length; i++) {
        const _el_p = _els_o[i];
        const _row_q = { _index: i + 1 };
          _row_q["Title"] = await _el_p.$eval("div.c-catalog__title", e => (e.textContent || '').trim()).catch(() => '');
          _row_q["Subtitle"] = await _el_p.$eval("div.c-catalog__subtitle", e => (e.textContent || '').trim()).catch(() => '');
          _row_q["catalog stat"] = await _el_p.$eval("div > div", e => (e.textContent || '').trim()).catch(() => '');
          _row_q["catalog score"] = await _el_p.$eval("span.c-catalog__score", e => (e.textContent || '').trim()).catch(() => '');
        _rows_r.push(_row_q);
      }
    }
    __results__["Catalog items"] = _rows_r;
    const _rows_v = [];
    {
      const _els_s = await page.$$("#panel-a > div:nth-child(2) div.entry-item");
      for (let i = 0; i < _els_s.length; i++) {
        const _el_t = _els_s[i];
        const _row_u = { _index: i + 1 };
          _row_u["Entry name"] = await _el_t.$eval("span.entry-name", e => (e.textContent || '').trim()).catch(() => '');
          _row_u["Entry value"] = await _el_t.$eval("span.entry-val", e => (e.textContent || '').trim()).catch(() => '');
        _rows_v.push(_row_u);
      }
    }
    __results__["Panels"] = _rows_v;
    const _rows_z = [];
    {
      const _els_w = await page.$$("div.option-card");
      for (let i = 0; i < _els_w.length; i++) {
        const _el_x = _els_w[i];
        const _row_y = { _index: i + 1 };
          _row_y["card title"] = await _el_x.$eval("div.option-name", e => (e.textContent || '').trim()).catch(() => '');
        _rows_z.push(_row_y);
      }
    }
    __results__["Cards"] = _rows_z;
    const _rows_13 = [];
    {
      const _els_10 = await page.$$("div._3xK9m");
      for (let i = 0; i < _els_10.length; i++) {
        const _el_11 = _els_10[i];
        const _row_12 = { _index: i + 1 };
          _row_12["Title"] = await _el_11.$eval("div._mNq4w", e => (e.textContent || '').trim()).catch(() => '');
          _row_12["Value"] = await _el_11.$eval("div._9wEm1", e => (e.textContent || '').trim()).catch(() => '');
        _rows_13.push(_row_12);
      }
    }
    __results__["Hash classes"] = _rows_13;
    const _rows_17 = [];
    {
      const _els_14 = await page.$$("div.feature-row");
      for (let i = 0; i < _els_14.length; i++) {
        const _el_15 = _els_14[i];
        const _row_16 = { _index: i + 1 };
          _row_16["Feature name"] = await _el_15.$eval("div.feature-name", e => (e.textContent || '').trim()).catch(() => '');
          _row_16["Feature plan"] = await _el_15.$eval("div.feature-plan", e => (e.textContent || '').trim()).catch(() => '');
        _rows_17.push(_row_16);
      }
    }
    __results__["Features"] = _rows_17;
    const _rows_1b = [];
    {
      const _els_18 = await page.$$("div.feed-post");
      for (let i = 0; i < _els_18.length; i++) {
        const _el_19 = _els_18[i];
        const _row_1a = { _index: i + 1 };
          _row_1a["User"] = await _el_19.$eval("div.post-user", e => (e.textContent || '').trim()).catch(() => '');
          _row_1a["Post body"] = await _el_19.$eval("div.post-body", e => (e.textContent || '').trim()).catch(() => '');
        _rows_1b.push(_row_1a);
      }
    }
    __results__["Posts"] = _rows_1b;
    const _rows_1f = [];
    {
      const _els_1c = await page.$$("#inline-demo div");
      for (let i = 0; i < _els_1c.length; i++) {
        const _el_1d = _els_1c[i];
        const _row_1e = { _index: i + 1 };
          _row_1e["Title"] = await _el_1d.$eval("div > div", e => (e.textContent || '').trim()).catch(() => '');
          _row_1e["Subtitle"] = await _el_1d.$eval("div > div", e => (e.textContent || '').trim()).catch(() => '');
          _row_1e["Temperature"] = await _el_1d.$eval("div:nth-child(3)", e => (e.textContent || '').trim()).catch(() => '');
        _rows_1f.push(_row_1e);
      }
    }
    __results__["No classes"] = _rows_1f;

  } catch (err) {
    console.error('❌ Workflow error:', err.message);
    process.exitCode = 1;
  } finally {
    await browser.close();
  }

  // Output collected extraction results
  if (Object.keys(__results__).length > 0) {
    console.log('');
    for (const [key, value] of Object.entries(__results__)) {
      if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object') {
        // Tabular data from ForEach loop — print as table
        console.log('\n── ' + key + ' ──');
        const cols = Object.keys(value[0]);
        const widths = cols.map(c => Math.max(c.length, ...value.map(r => String(r[c] ?? '').length)));
        const hr = widths.map(w => '─'.repeat(w + 2)).join('┼');
        const header = cols.map((c, i) => ' ' + c.padEnd(widths[i]) + ' ').join('│');
        console.log(header);
        console.log(hr);
        value.forEach(row => {
          const line = cols.map((c, i) => ' ' + String(row[c] ?? '').padEnd(widths[i]) + ' ').join('│');
          console.log(line);
        });
      } else {
        console.log('\n── ' + key + ' ──');
        console.log(JSON.stringify(value, null, 2));
      }
    }
    console.log('\nWORKFLOW_RESULTS:' + JSON.stringify(__results__));
  }
}

run().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
