'use strict';

/* ===========================================================================
   db/schema.js
   ---------------------------------------------------------------------------
   Single source of truth for the application schema, emitted per dialect.

   The only real differences between the SQLite and Postgres DDL are:
     • the auto-increment primary key declaration, and
     • timestamp defaults (we standardise on CURRENT_TIMESTAMP, which both
       engines support, instead of SQLite's datetime('now')).

   Everything else — TEXT, INTEGER, FOREIGN KEY, indexes, IF NOT EXISTS — is
   identical across the two engines, so we template the PK and share the rest.

   Booleans are stored as INTEGER 0/1 (portable; we don't use a dialect
   BOOLEAN). Timestamps are stored as text/timestamp via CURRENT_TIMESTAMP.
   ========================================================================= */

// Auto-increment integer primary key, per dialect.
function pk(dialect) {
  return dialect === 'postgres'
    ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    : 'INTEGER PRIMARY KEY AUTOINCREMENT';
}

// Plain integer foreign-key column type. SQLite is dynamically typed so
// INTEGER is fine; Postgres needs BIGINT to match the BIGINT identity PKs.
function fk(dialect) {
  return dialect === 'postgres' ? 'BIGINT' : 'INTEGER';
}

/**
 * Return the ordered list of DDL statements that build the full schema for the
 * given dialect. Every statement is idempotent (IF NOT EXISTS), so running it
 * against an already-provisioned database is a no-op — which is exactly what
 * lets it run safely alongside the legacy synchronous db/index.js during the
 * incremental migration.
 */
function statements(dialect) {
  const ID = pk(dialect);
  const FK = fk(dialect);

  return [
    `CREATE TABLE IF NOT EXISTS users (
       id            ${ID},
       username      TEXT NOT NULL UNIQUE,
       password_hash TEXT NOT NULL,
       created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
     )`,

    `CREATE TABLE IF NOT EXISTS workflows (
       id          ${ID},
       user_id     ${FK} NOT NULL,
       name        TEXT NOT NULL,
       steps_json  TEXT NOT NULL,
       meta_json   TEXT,
       created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
     )`,
    `CREATE INDEX IF NOT EXISTS idx_workflows_user ON workflows(user_id)`,

    `CREATE TABLE IF NOT EXISTS custom_actions (
       id           ${ID},
       user_id      ${FK} NOT NULL,
       name         TEXT NOT NULL,
       description  TEXT,
       inputs_json  TEXT NOT NULL DEFAULT '[]',
       outputs_json TEXT NOT NULL DEFAULT '[]',
       code         TEXT NOT NULL DEFAULT '',
       created_at   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
     )`,
    `CREATE INDEX IF NOT EXISTS idx_custom_actions_user ON custom_actions(user_id)`,

    `CREATE TABLE IF NOT EXISTS schedules (
       id               ${ID},
       user_id          ${FK} NOT NULL,
       workflow_id      ${FK} NOT NULL,
       interval_minutes INTEGER NOT NULL,
       is_active        INTEGER NOT NULL DEFAULT 1,
       anchor_at        TEXT,
       next_run_at      TEXT,
       last_run_at      TEXT,
       created_at       TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at       TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE,
       FOREIGN KEY (user_id)     REFERENCES users(id)     ON DELETE CASCADE
     )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_schedules_workflow ON schedules(workflow_id)`,
    `CREATE INDEX IF NOT EXISTS idx_schedules_user ON schedules(user_id)`,
    `CREATE INDEX IF NOT EXISTS idx_schedules_next ON schedules(is_active, next_run_at)`,

    `CREATE TABLE IF NOT EXISTS runs (
       id                ${ID},
       user_id           ${FK} NOT NULL,
       workflow_id       ${FK} NOT NULL,
       schedule_id       ${FK},
       parent_run_id     ${FK},
       trigger           TEXT NOT NULL DEFAULT 'manual',
       status            TEXT NOT NULL DEFAULT 'running',
       started_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       finished_at       TEXT,
       duration_ms       INTEGER,
       results_json      TEXT,
       error_message     TEXT,
       error_category    TEXT,
       failed_step_id    TEXT,
       failed_step_type  TEXT,
       failed_step_label TEXT,
       ai_summary        TEXT,
       retry_count       INTEGER NOT NULL DEFAULT 0,
       patched_steps_json TEXT,
       version_id        ${FK},
       FOREIGN KEY (workflow_id) REFERENCES workflows(id)  ON DELETE CASCADE,
       FOREIGN KEY (user_id)     REFERENCES users(id)      ON DELETE CASCADE,
       FOREIGN KEY (schedule_id) REFERENCES schedules(id)  ON DELETE SET NULL
     )`,
    `CREATE INDEX IF NOT EXISTS idx_runs_workflow ON runs(workflow_id, started_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_runs_user     ON runs(user_id, started_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_runs_status   ON runs(status)`,

    `CREATE TABLE IF NOT EXISTS run_logs (
       id     ${ID},
       run_id ${FK} NOT NULL,
       seq    INTEGER NOT NULL,
       level  TEXT NOT NULL,
       line   TEXT NOT NULL,
       FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
     )`,
    `CREATE INDEX IF NOT EXISTS idx_run_logs_run ON run_logs(run_id, seq)`,

    `CREATE TABLE IF NOT EXISTS run_repairs (
       id               ${ID},
       run_id           ${FK} NOT NULL,
       workflow_id      ${FK} NOT NULL,
       step_id          TEXT NOT NULL,
       step_type        TEXT,
       attempt          INTEGER NOT NULL,
       error_message    TEXT,
       original_params  TEXT,
       suggested_params TEXT,
       explanation      TEXT,
       confidence       TEXT,
       applied          INTEGER NOT NULL DEFAULT 0,
       verified         INTEGER NOT NULL DEFAULT 0,
       llm_error        TEXT,
       repair_kind      TEXT,
       evidence_json    TEXT,
       auto_adopted     INTEGER NOT NULL DEFAULT 0,
       created_at       TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (run_id)      REFERENCES runs(id)      ON DELETE CASCADE,
       FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE
     )`,
    `CREATE INDEX IF NOT EXISTS idx_run_repairs_run ON run_repairs(run_id)`,

    `CREATE TABLE IF NOT EXISTS workflow_versions (
       id          ${ID},
       workflow_id ${FK} NOT NULL,
       user_id     ${FK} NOT NULL,
       hash        TEXT NOT NULL,
       steps_json  TEXT NOT NULL,
       meta_json   TEXT,
       source      TEXT,
       created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE,
       FOREIGN KEY (user_id)     REFERENCES users(id)     ON DELETE CASCADE
     )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_wfver_unique ON workflow_versions(workflow_id, hash)`,
    `CREATE INDEX IF NOT EXISTS idx_wfver_workflow ON workflow_versions(workflow_id, id DESC)`,
  ];
}

module.exports = { statements, pk, fk };
